export const FETCH_USER_DATA = "FETCH_USER_DATA";
// Mails
export const SWITCH_SINGLE_MAIL_CHECKBOX = "SWITCH_SINGLE_MAIL_CHECKBOX";
export const SWITCH_FAVORITE_MESSAGE = "SWITCH_FAVORITE_MESSAGE";
// Sorting bar
export const SWITCH_ALL_MAILS_SELECTING = "SWITCH_ALL_MAILS_SELECTING";
export const SORT_MAILS_BY_TYPE = "SORT_MAILS_BY_TYPE";
export const CHANGE_SORTING_DIRECTION = "CHANGE_SORTING_DIRECTION";
// Navbar folders actions
export const CREATE_NEW_USER_FOLDER = "CREATE_NEW_USER_FOLDER";
// Header menu button switch
export const SWITCH_MENU_SIDEBAR_VISIBILITY = "SWITCH_MENU_SIDEBAR_VISIBILITY";
// Toolbar actions
export const CHANGE_MAILS_DIRECTORY_TO_SPECIFIC_TYPE = "CHANGE_MAILS_DIRECTORY_TO_SPECIFIC_TYPE";
export const SELECT_ALL_MAILS_IN_FOLDER = "SELECT_ALL_MAILS_IN_FOLDER";
export const SELECT_UNREAD_MESSAGES_IN_FOLDER = "SELECT_UNREAD_MESSAGES_IN_FOLDER";
export const SELECT_READED_MESSAGES_IN_FOLDER = "SELECT_READED_MESSAGES_IN_FOLDER";
export const UNSELECT_ALL_MAILS_IN_FOLDER = "UNSELECT_ALL_MAILS_IN_FOLDER";
// sidebar navigation
export const UNSELECT_MAILS = "UNSELECT_MAILS";
export const RESET_SORTING_BAR = "RESET_SORTING_BAR";