export const FETCH_USER_DATA = "FETCH_USER_DATA";
// Mails
export const SWITCH_SINGLE_MAIL_CHECKBOX = "SWITCH_SINGLE_MAIL_CHECKBOX";
export const SWITCH_FAVORITE_MESSAGE = "SWITCH_FAVORITE_MESSAGE";
// Segregation bar
export const SWITCH_ALL_MAILS_SELECTING = "SWITCH_ALL_MAILS_SELECTING";