export const FETCH_USER_DATA = "FETCH_USER_DATA";
// Mails
export const SWITCH_SINGLE_MAIL_CHECKBOX = "SWITCH_SINGLE_MAIL_CHECKBOX";
export const SWITCH_FAVORITE_MESSAGE = "SWITCH_FAVORITE_MESSAGE";
// Sorting bar
export const SWITCH_ALL_MAILS_SELECTING = "SWITCH_ALL_MAILS_SELECTING";
export const SORT_MAILS_BY_TYPE = "SORT_MAILS_BY_TYPE";
export const CHANGE_SORTING_DIRECTION = "CHANGE_SORTING_DIRECTION";